import { StyleSheet } from 'react-native';
import { normalize, verticalScale } from '../../Utils/Helpers/normalize';
import Colorpath from '../../Themes/Colorpath';
import { Fonts, theme } from '../../Themes';
export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FAFBFF',
    },
    qBankHeaderBackground: {
        backgroundColor: theme.colors.primary,
        paddingBottom: verticalScale(16),
    },
    qBankHeader: {
        backgroundColor: 'transparent',
    },
    qBankSearchWrap: {
        paddingHorizontal: normalize(20),
        marginBottom: verticalScale(0),
    },
    qBankZeroMargin: {
        marginBottom: 0,
    },
    qBankSearchInput: {
        backgroundColor: '#FFFFFF',
        borderColor: '#D8E6F8',
        borderRadius: normalize(12),
    },
    qBankSearchText: {
        color: theme.colors.text,
        fontSize: normalize(14),
    },
    qBankSurfaceCard: {
        backgroundColor: '#F8FAFC',
        marginHorizontal: normalize(16),
        marginBottom: verticalScale(14),
        borderRadius: normalize(24),
        paddingVertical: verticalScale(14),
        paddingHorizontal: normalize(12),
        borderColor: Colorpath.Primary,
        borderWidth: 0.5,
        // shadowColor: '#0F172A',
        // shadowOffset: { width: 0, height: 8 },
        // shadowOpacity: 0.05,
        // shadowRadius: 18,
        // elevation: 3,
    },
    segmentedControl: {
        flexDirection: 'row',
        backgroundColor: '#EAF2FB',
        borderRadius: normalize(18),
        padding: normalize(4),
        marginBottom: verticalScale(14),
    },
    segmentButtonWrap: {
        flex: 1,
        marginHorizontal: 0,
    },
    segmentButton: {
        minHeight: verticalScale(42),
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: normalize(14),
        borderWidth: 1,
        overflow: 'hidden',
    },
    segmentButtonActive: {
        shadowColor: '#0F172A',
        shadowOpacity: 0.18,
        shadowRadius: 8,
        elevation: 2,
    },
    segmentText: {
        color: '#475467',
        fontFamily: Fonts.intersemibold,
        fontSize: normalize(12),
        fontWeight: '700',
        textAlign: 'center',
        letterSpacing: 0.2,
    },
    segmentTextRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: normalize(6),
    },
    segmentInfoButton: {
        width: normalize(18),
        height: normalize(18),
        borderRadius: normalize(9),
        alignItems: 'center',
        justifyContent: 'center',
    },
    segmentTextActive: {
        color: theme.colors.white,
    },

    viewMoreBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: verticalScale(12),
        backgroundColor: '#F8FAFC',
        borderRadius: normalize(8),
        marginTop: verticalScale(8),
        borderWidth: 1,
        borderColor: '#E2E8F0',
    },
    viewMoreBtnText: {
        color: '#1D4ED8',
        fontSize: normalize(13),
        fontWeight: '600',
        marginRight: normalize(6),
    },

    qBankCardPressable: {
        width: '100%',
        marginBottom: verticalScale(6),
    },
    qBankCard: {
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: normalize(12),
        paddingVertical: verticalScale(12),
        borderRadius: normalize(18),
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.18)',
        overflow: 'hidden',
        minHeight: verticalScale(84),
        shadowOpacity: 0.12,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 4 },
        elevation: 3,
    },
    qBankIconContainer: {
        width: normalize(44),
        height: normalize(44),
        borderRadius: normalize(16),
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: normalize(10),
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.32)',
        shadowOpacity: 0.18,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
        elevation: 4,
        overflow: 'hidden',
    },
    qBankIconInner: {
        width: '100%',
        height: '100%',
        borderRadius: normalize(15),
        alignItems: 'center',
        justifyContent: 'center',
    },
    qBankCardContent: {
        flex: 1,
        paddingRight: normalize(8),
    },
    qBankCardTitle: {
        color: '#0F172A',
        fontSize: normalize(15),
        fontWeight: '800',
        marginBottom: verticalScale(4),
    },
    qBankCardTitleLight: {
        color: '#FFFFFF',
    },
    qBankCardSubtitle: {
        color: '#64748B',
        fontSize: normalize(11),
        fontWeight: '500',
    },
    qBankCardSubtitleLight: {
        color: 'rgba(255,255,255,0.88)',
    },

    qBankArrowMark: {
        fontSize: normalize(18),
        fontWeight: '900',
        color: '#FFFFFF',
        letterSpacing: 1.4,
        marginLeft: normalize(6),
    },

    detailHeader: {
        backgroundColor: Colorpath.Primary,
        borderBottomLeftRadius: normalize(20),
        borderBottomRightRadius: normalize(20),
    },
    detailHeaderContent: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: normalize(20),
        paddingTop: verticalScale(12),
        paddingBottom: verticalScale(20),
    },
    backBtn: {
        width: normalize(36),
        height: normalize(36),
        borderRadius: normalize(18),
        backgroundColor: 'rgba(255, 255, 255, 0.15)',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: normalize(16),
    },
    headerTextColumn: {
        flex: 1,
    },
    headerTagline: {
        fontSize: normalize(10),
        fontWeight: 'bold',
        color: 'rgba(255, 255, 255, 0.6)',
        letterSpacing: 1,
    },
    headerMainTitle: {
        fontSize: normalize(20),
        fontWeight: '800',
        color: '#FFFFFF',
        marginTop: verticalScale(2),
    },
    detailSubtitle: {
        fontSize: normalize(11),
        color: 'rgba(255, 255, 255, 0.85)',
        marginTop: verticalScale(4),
    },
    headerRightIcon: {
        width: normalize(36),
        height: normalize(36),
        borderRadius: normalize(18),
        backgroundColor: '#FFFFFF',
        justifyContent: 'center',
        alignItems: 'center',
    },
    detailScrollContent: {
        paddingHorizontal: normalize(20),
        paddingTop: verticalScale(20),
    },
    detailSearchWrap: {
        marginBottom: verticalScale(14),
    },
    detailSearchZeroMargin: {
        marginBottom: 0,
    },
    detailSearchInput: {
        backgroundColor: '#FFFFFF',
        borderColor: '#D8E6F8',
        borderRadius: normalize(12),
    },
    detailSearchText: {
        color: theme.colors.text,
        fontSize: normalize(14),
    },
    sectionTitle: {
        fontSize: normalize(16),
        fontWeight: '800',
        color: '#1F2937',
        marginBottom: verticalScale(12),
    },

    subjectSubtitle: {
        fontSize: normalize(12),
        color: '#6B7280',
        marginTop: -verticalScale(8),
        marginBottom: verticalScale(12),
    },
    dynamicTabsScrollContent: {
        paddingVertical: verticalScale(6),
        paddingHorizontal: normalize(6),
        gap: normalize(10),
    },
    dynamicTabsCard: {
        borderRadius: normalize(22),
        borderWidth: 1,
        borderColor: 'rgba(15, 118, 110, 0.10)',
        paddingVertical: verticalScale(8),
        paddingHorizontal: normalize(8),
        marginBottom: verticalScale(10),
        shadowColor: '#0F172A',
        shadowOpacity: 0.04,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 4 },
        elevation: 1,
        overflow: 'hidden',
    },
    dynamicTabPressable: {
        marginRight: normalize(10),
    },
    dynamicTabItem: {
        minWidth: normalize(112),
        paddingHorizontal: normalize(16),
        paddingVertical: verticalScale(10),
        borderRadius: normalize(999),
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: 'rgba(15, 118, 110, 0.08)',
    },
    dynamicTabItemActive: {
        borderColor: 'rgba(255,255,255,0.18)',
        transform: [{ scale: 1.02 }],
    },
    dynamicTabItemActiveGlow: {
        borderColor: 'rgba(255,255,255,0.16)',
        shadowColor: '#0F172A',
        shadowOpacity: 0.1,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
        elevation: 2,
    },
    dynamicTabText: {
        fontSize: normalize(13),
        fontWeight: '800',
        color: '#475467',
        letterSpacing: 0.4,
    },
    dynamicTabTextActive: {
        color: '#FFFFFF',
        textShadowColor: 'rgba(0,0,0,0.12)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 2,
    },
    dynamicTabIndicator: {
        height: verticalScale(6),
        width: normalize(26),
        borderRadius: normalize(999),
        backgroundColor: 'rgba(255,255,255,0.24)',
        marginTop: verticalScale(8),
    },
    dynamicTabIndicatorActive: {
        backgroundColor: 'rgba(255,255,255,0.92)',
    },

    topicRow: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    topicDot: {
        width: normalize(10),
        height: normalize(10),
        borderRadius: normalize(5),
        backgroundColor: '#9AE6B4',
        marginRight: normalize(10),
    },
    topicTitle: {
        fontSize: normalize(14),
        fontWeight: '800',
        color: '#475467',
    },

    quizCardsWrap: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        gap: normalize(10),
    },
    quizCardPressable: {
        width: '48%',
        minWidth: normalize(140),
    },
    quizCard: {
        width: '100%',
        borderRadius: normalize(16),
        padding: normalize(10),
        borderWidth: 1,
        borderColor: '#E2E8F0',
        overflow: 'hidden',
        minHeight: verticalScale(106),
    },
    courseCardPressable: {
        width: '100%',
    },
    courseSectionBanner: {
        borderRadius: normalize(22),
        padding: normalize(16),
        marginBottom: verticalScale(16),
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
    },
    courseSectionBannerPillOnly: {
        alignItems: 'center',
        justifyContent: 'center',
    },

    courseSectionBannerPillValue: {
        fontSize: normalize(18),
        fontWeight: '900',
        color: '#FFFFFF',
        lineHeight: normalize(20),
    },
    courseSectionBannerPillLabel: {
        fontSize: normalize(9),
        fontWeight: '800',
        color: 'rgba(255,255,255,0.88)',
        letterSpacing: 0.8,
        marginTop: verticalScale(2),
    },

    quizCardTitle: {
        fontSize: normalize(16),
        fontWeight: '800',
        color: '#1D2939',
        marginBottom: verticalScale(2),
    },

    quizMetaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        marginBottom: verticalScale(16),
    },
    quizMetaItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: normalize(14),
    },
    quizMetaText: {
        fontSize: normalize(12),
        color: '#667085',
        marginLeft: normalize(6),
        fontWeight: '600',
    },

    quizActionButton: {
        height: verticalScale(34),
        borderRadius: normalize(10),
        backgroundColor: '#0F766E',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: normalize(8),
        shadowColor: '#0F172A',
        shadowOpacity: 0.08,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 3 },
        elevation: 1,
    },
    quizActionButtonDisabled: {
        opacity: 0.7,
    },
    quizActionText: {
        color: '#FFFFFF',
        fontSize: normalize(13),
        fontWeight: '800',
    },
    quizViewOnlyTag: {
        height: verticalScale(34),
        borderRadius: normalize(10),
        backgroundColor: 'rgba(255,255,255,0.16)',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.20)',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: normalize(6),
    },
    quizViewOnlyText: {
        color: '#667085',
        fontSize: normalize(13),
        fontWeight: '700',
    },

    noteViewerContainer: {
        flex: 1,
        backgroundColor: '#F8FAFC',
    },
    noteViewerSafeArea: {
        backgroundColor: '#FFFFFF',
    },
    noteViewerHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: normalize(20),
        paddingVertical: verticalScale(14),
        borderBottomWidth: 1,
        borderBottomColor: '#E2E8F0',
        backgroundColor: '#FFFFFF',
    },
    noteViewerCloseBtn: {
        width: normalize(40),
        height: normalize(40),
        borderRadius: normalize(20),
        justifyContent: 'center',
        alignItems: 'center',
    },
    noteViewerHeaderText: {
        flex: 1,
    },
    noteViewerLabel: {
        alignSelf: 'flex-start',
        borderRadius: normalize(999),
        borderWidth: 1,
        borderColor: '#99F6E4',
        backgroundColor: '#F0FDFA',
        color: Colorpath.Primary,
        fontSize: normalize(10),
        fontWeight: '800',
        letterSpacing: 1,
        paddingHorizontal: normalize(12),
        paddingVertical: verticalScale(5),
        marginBottom: verticalScale(10),
    },
    noteViewerTitle: {
        fontSize: normalize(20),
        fontWeight: '800',
        color: '#0F172A',
        marginBottom: verticalScale(2),
    },
    noteViewerSubtitle: {
        fontSize: normalize(12),
        color: '#64748B',
    },

    noteViewerStateBox: {
        minHeight: verticalScale(220),
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: normalize(18),
        borderWidth: 1,
        borderColor: '#E2E8F0',
        paddingHorizontal: normalize(16),
    },
    noteViewerStateText: {
        marginTop: verticalScale(12),
        fontSize: normalize(13),
        color: '#64748B',
        textAlign: 'center',
    },
    noteViewerLayout: {
        flex: 1,
        flexDirection: 'row',
        flexWrap: 'nowrap',
    },
    noteViewerLeftPanel: {
        width: '35%',
        backgroundColor: '#FFFFFF',
        borderRightWidth: 1,
        borderRightColor: '#E5E7EB',
        padding: normalize(18),
    },
    noteViewerRightPanel: {
        width: '65%',
        padding: normalize(18),
        backgroundColor: '#F8FAFC',
    },
    noteViewerPanelLabel: {
        fontSize: normalize(12),
        fontWeight: '800',
        color: '#667085',
        letterSpacing: 2,
        marginBottom: verticalScale(14),
    },
    noteViewerListContent: {
        paddingBottom: verticalScale(12),
    },
    noteViewerListItem: {
        minHeight: verticalScale(60),
        borderRadius: normalize(18),
        borderWidth: 1,
        borderColor: '#E5E7EB',
        backgroundColor: '#FFFFFF',
        paddingHorizontal: normalize(14),
        paddingVertical: verticalScale(14),
        flexDirection: 'row',
        alignItems: 'center',
        gap: normalize(10),
    },
    noteViewerListItemActive: {
        backgroundColor: Colorpath.Primary,
        borderColor: Colorpath.Primary,
    },
    noteViewerListIndex: {
        fontSize: normalize(14),
        fontWeight: '800',
        color: '#98A2B3',
        width: normalize(22),
    },
    noteViewerListIndexActive: {
        color: '#FFFFFF',
    },
    noteViewerListText: {
        flex: 1,
        fontSize: normalize(14),
        fontWeight: '700',
        color: '#344054',
    },
    noteViewerListTextActive: {
        color: '#FFFFFF',
    },
    noteViewerDetailScroll: {
        paddingBottom: verticalScale(24),
    },
    noteViewerDetailCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: normalize(22),
        borderWidth: 1,
        borderColor: '#D0D5DD',
        padding: normalize(20),
    },
    noteViewerDetailTopRow: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: normalize(12),
        marginBottom: verticalScale(12),
    },
    noteViewerDetailTag: {
        paddingHorizontal: normalize(12),
        paddingVertical: verticalScale(5),
        borderRadius: normalize(999),
        backgroundColor: '#F0FDFA',
        color: Colorpath.Primary,
        fontSize: normalize(10),
        fontWeight: '800',
        letterSpacing: 0.6,
    },
    noteViewerDetailTitle: {
        flex: 1,
        fontSize: normalize(20),
        fontWeight: '800',
        color: '#101828',
    },
    noteViewerDetailBody: {
        fontSize: normalize(14),
        color: '#334155',
        lineHeight: normalize(22),
    },
    noteViewerDetailHint: {
        marginTop: verticalScale(12),
        fontSize: normalize(12),
        color: '#64748B',
        fontWeight: '600',
    },
    noteViewerViewButton: {
        alignSelf: 'flex-start',
        marginTop: verticalScale(18),
        backgroundColor: Colorpath.Primary,
        borderRadius: normalize(12),
        paddingHorizontal: normalize(16),
        height: verticalScale(44),
        flexDirection: 'row',
        alignItems: 'center',
        gap: normalize(8),
    },
    noteViewerViewButtonText: {
        color: '#FFFFFF',
        fontSize: normalize(14),
        fontWeight: '800',
    },
    notePageViewerContainer: {
        flex: 1,
        backgroundColor: '#F8FAFC',
    },
    notePageViewerSafeArea: {
        backgroundColor: '#FFFFFF',
    },
    notePageViewerHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        paddingHorizontal: normalize(20),
        paddingVertical: verticalScale(16),
        borderBottomWidth: 1,
        borderBottomColor: '#E2E8F0',
    },
    notePageViewerHeaderText: {
        flex: 1,
    },
    notePageViewerLabel: {
        alignSelf: 'flex-start',
        borderRadius: normalize(999),
        borderWidth: 1,
        borderColor: '#99F6E4',
        backgroundColor: '#F0FDFA',
        color: Colorpath.Primary,
        fontSize: normalize(10),
        fontWeight: '800',
        letterSpacing: 1,
        paddingHorizontal: normalize(12),
        paddingVertical: verticalScale(5),
        marginBottom: verticalScale(10),
    },
    notePageViewerTitle: {
        fontSize: normalize(22),
        fontWeight: '800',
        color: '#0F172A',
    },
    notePageViewerCloseBtn: {
        width: normalize(40),
        height: normalize(40),
        borderRadius: normalize(20),
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F1F5F9',
    },

    notePageViewerContent: {
        flex: 1,
        padding: normalize(18),
    },
    notePageViewerCard: {
        flex: 1,
        backgroundColor: '#FFFFFF',
        borderRadius: normalize(22),
        borderWidth: 1,
        borderColor: '#D0D5DD',
        overflow: 'hidden',
    },
    notePageViewerWebView: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    notePageViewerEmptyState: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: normalize(20),
    },
    notePageViewerBody: {
        fontSize: normalize(14),
        color: '#334155',
        lineHeight: normalize(22),
    },

    courseLayout: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: normalize(16),
        marginTop: verticalScale(8),
    },
    courseLeftPanel: {
        width: '30%',
        minWidth: normalize(180),
        backgroundColor: '#FFFFFF',
        borderRadius: normalize(20),
        borderWidth: 1,
        borderColor: '#E5E7EB',
        padding: normalize(14),
        shadowColor: '#0F172A',
        shadowOpacity: 0.04,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 4 },
        elevation: 1,
    },
    coursePanelHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: verticalScale(12),
    },
    courseRightPanel: {
        flex: 1,
        backgroundColor: '#FFFFFF',
        borderRadius: normalize(20),
        borderWidth: 1,
        borderColor: '#E5E7EB',
        padding: normalize(14),
        shadowColor: '#0F172A',
        shadowOpacity: 0.04,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 4 },
        elevation: 1,
    },
    coursePanelLabel: {
        fontSize: normalize(11),
        fontWeight: '800',
        color: '#667085',
        letterSpacing: 1.2,
        textTransform: 'uppercase',
    },
    coursePanelCountPill: {
        minWidth: normalize(32),
        height: verticalScale(28),
        borderRadius: normalize(999),
        paddingHorizontal: normalize(10),
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#ECFDF5',
        borderWidth: 1,
        borderColor: '#A7F3D0',
    },
    coursePanelCountText: {
        fontSize: normalize(11),
        fontWeight: '900',
        color: Colorpath.Primary,
    },
    courseSectionItemPressable: {
        borderRadius: normalize(18),
        overflow: 'hidden',
    },
    courseSectionItem: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(15, 118, 110, 0.10)',
        backgroundColor: '#F8FAFC',
        paddingHorizontal: normalize(14),
        paddingVertical: verticalScale(14),
        minHeight: verticalScale(58),
        justifyContent: 'space-between',
        gap: normalize(12),
    },
    courseSectionItemActive: {
        borderColor: 'rgba(255,255,255,0.14)',
    },
    courseSectionText: {
        flex: 1,
        fontSize: normalize(14),
        fontWeight: '700',
        color: '#475467',
    },
    courseSectionTextActive: {
        color: '#FFFFFF',
    },
    courseSectionItemDot: {
        width: normalize(10),
        height: normalize(10),
        borderRadius: normalize(5),
        backgroundColor: '#C7D2FE',
    },
    courseSectionItemDotActive: {
        backgroundColor: '#FFFFFF',
    },
    courseCard: {
        width: '100%',
        minHeight: verticalScale(164),
        borderRadius: normalize(20),
        borderWidth: 1,
        borderColor: 'rgba(15, 118, 110, 0.10)',
        padding: normalize(16),
        justifyContent: 'space-between',
        overflow: 'hidden',
        shadowColor: '#0F172A',
        shadowOpacity: 0.05,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 4 },
        elevation: 2,
    },
    courseCardBadge: {
        alignSelf: 'flex-start',
        paddingHorizontal: normalize(10),
        paddingVertical: verticalScale(4),
        borderRadius: normalize(999),
        backgroundColor: '#F0FDFA',
        borderWidth: 1,
        borderColor: '#99F6E4',
        marginBottom: verticalScale(10),
    },
    courseCardBadgeText: {
        fontSize: normalize(10),
        fontWeight: '800',
        color: Colorpath.Primary,
        letterSpacing: 0.6,
    },
    courseCardTitle: {
        fontSize: normalize(16),
        fontWeight: '800',
        color: '#101828',
        marginBottom: verticalScale(6),
    },
    courseCardSubtitle: {
        fontSize: normalize(12),
        color: '#667085',
        lineHeight: normalize(18),
        marginBottom: verticalScale(12),
    },
    courseCardFooter: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: normalize(10),
    },
    courseCardFooterText: {
        flex: 1,
        fontSize: normalize(12),
        fontWeight: '700',
        color: '#475467',
    },
    videoCardTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: normalize(8),
        marginBottom: verticalScale(10),
    },
    emptyStateBox: {
        minHeight: verticalScale(220),
        borderRadius: normalize(18),
        borderWidth: 1,
        borderColor: '#E5E7EB',
        backgroundColor: '#F8FAFC',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: normalize(16),
    },
    emptyStateText: {
        marginTop: verticalScale(10),
        fontSize: normalize(13),
        color: '#667085',
        fontWeight: '600',
        textAlign: 'center',
    },
    questionBankContainer: {
        flex: 1,
        backgroundColor: '#F8FAFC',
    },
    questionBankSafeArea: {
        backgroundColor: '#FFFFFF',
    },
    questionBankHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        paddingHorizontal: normalize(20),
        paddingVertical: verticalScale(16),
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
        gap: normalize(14),
    },
    questionBankCloseBtn: {
        width: normalize(40),
        height: normalize(40),
        borderRadius: normalize(20),
        justifyContent: 'center',
        alignItems: 'center',
    },
    questionBankHeaderText: {
        flex: 1,
    },
    questionBankLabel: {
        alignSelf: 'flex-start',
        borderRadius: normalize(999),
        borderWidth: 1,
        borderColor: '#99F6E4',
        backgroundColor: '#F0FDFA',
        color: Colorpath.Primary,
        fontSize: normalize(10),
        fontWeight: '800',
        letterSpacing: 1,
        paddingHorizontal: normalize(12),
        paddingVertical: verticalScale(5),
        marginBottom: verticalScale(10),
    },
    questionBankTitle: {
        fontSize: normalize(22),
        fontWeight: '800',
        color: '#101828',
        marginBottom: verticalScale(4),
    },
    questionBankSubtitle: {
        fontSize: normalize(12),
        color: '#667085',
        fontWeight: '600',
        textTransform: 'uppercase',
    },
    questionBankLoadingState: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        gap: normalize(10),
    },

    questionBankEmptyState: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        padding: normalize(20),
    },
    questionBankEmptyText: {
        marginTop: verticalScale(10),
        fontSize: normalize(13),
        color: '#667085',
        fontWeight: '600',
        textAlign: 'center',
    },
    questionBankLayout: {
        flex: 1,
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    questionBankLeftPanel: {
        width: '30%',
        minWidth: normalize(180),
        backgroundColor: '#FFFFFF',
        borderRightWidth: 1,
        borderRightColor: '#E5E7EB',
        padding: normalize(18),
    },
    questionBankRightPanel: {
        flex: 1,
        padding: normalize(18),
        backgroundColor: '#F8FAFC',
    },
    questionBankPanelLabel: {
        fontSize: normalize(12),
        fontWeight: '800',
        color: '#667085',
        letterSpacing: 2,
        marginBottom: verticalScale(14),
    },
    questionBankListContent: {
        paddingBottom: verticalScale(12),
    },
    questionBankListItem: {
        minHeight: verticalScale(60),
        borderRadius: normalize(18),
        borderWidth: 1,
        borderColor: '#E5E7EB',
        backgroundColor: '#FFFFFF',
        paddingHorizontal: normalize(14),
        paddingVertical: verticalScale(14),
        flexDirection: 'row',
        alignItems: 'center',
        gap: normalize(10),
    },
    questionBankListItemActive: {
        backgroundColor: Colorpath.Primary,
        borderColor: Colorpath.Primary,
    },

    questionBankListIndex: {
        fontSize: normalize(14),
        fontWeight: '800',
        color: '#98A2B3',
        width: normalize(22),
    },
    questionBankListIndexActive: {
        color: '#FFFFFF',
    },
    questionBankListText: {
        flex: 1,
        fontSize: normalize(14),
        fontWeight: '700',
        color: '#344054',
    },
    questionBankListTextActive: {
        color: '#FFFFFF',
    },
    questionBankDetailScroll: {
        paddingBottom: verticalScale(24),
    },
    questionBankDetailCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: normalize(22),
        borderWidth: 1,
        borderColor: '#D0D5DD',
        padding: normalize(20),
    },
    questionBankDetailTopRow: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: normalize(12),
        marginBottom: verticalScale(12),
    },
    questionBankDetailTag: {
        paddingHorizontal: normalize(12),
        paddingVertical: verticalScale(5),
        borderRadius: normalize(999),
        backgroundColor: '#F0FDFA',
        color: Colorpath.Primary,
        fontSize: normalize(10),
        fontWeight: '800',
        letterSpacing: 0.6,
    },
    questionBankDetailTitle: {
        flex: 1,
        fontSize: normalize(20),
        fontWeight: '800',
        color: '#101828',
    },
    questionBankYearText: {
        fontSize: normalize(12),
        color: '#667085',
        fontWeight: '600',
        marginBottom: verticalScale(16),
    },
    questionBankOptionsWrap: {
        marginTop: verticalScale(6),
        marginBottom: verticalScale(18),
        gap: verticalScale(10),
    },
    questionBankOptionRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: normalize(10),
    },
    questionBankOptionDot: {
        width: normalize(10),
        height: normalize(10),
        borderRadius: normalize(5),
        backgroundColor: Colorpath.Primary,
        marginTop: verticalScale(5),
    },
    questionBankOptionText: {
        flex: 1,
        fontSize: normalize(14),
        color: '#344054',
        lineHeight: normalize(22),
    },
    questionBankToggleBtn: {
        alignSelf: 'flex-start',
        flexDirection: 'row',
        alignItems: 'center',
        gap: normalize(8),
        borderRadius: normalize(999),
        borderWidth: 1,
        borderColor: '#99F6E4',
        paddingHorizontal: normalize(16),
        paddingVertical: verticalScale(10),
        marginBottom: verticalScale(18),
    },
    questionBankToggleText: {
        fontSize: normalize(13),
        fontWeight: '800',
        color: Colorpath.Primary,
    },

    questionAnswerContainer: {
        flex: 1,
        backgroundColor: '#F8FAFC',
    },
    questionAnswerSafeArea: {
        backgroundColor: '#FFFFFF',
    },
    questionAnswerHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        paddingHorizontal: normalize(20),
        paddingVertical: verticalScale(16),
        borderBottomWidth: 1,
        borderBottomColor: '#E2E8F0',
    },
    questionAnswerHeaderText: {
        flex: 1,
    },
    questionAnswerLabel: {
        alignSelf: 'flex-start',
        borderRadius: normalize(999),
        borderWidth: 1,
        borderColor: '#99F6E4',
        backgroundColor: '#F0FDFA',
        color: Colorpath.Primary,
        fontSize: normalize(10),
        fontWeight: '800',
        letterSpacing: 1,
        paddingHorizontal: normalize(12),
        paddingVertical: verticalScale(5),
        marginBottom: verticalScale(10),
    },
    questionAnswerTitle: {
        fontSize: normalize(22),
        fontWeight: '800',
        color: '#0F172A',
        marginBottom: verticalScale(4),
    },
    questionAnswerSubtitle: {
        fontSize: normalize(12),
        color: '#64748B',
        fontWeight: '600',
        textTransform: 'uppercase',
    },
    questionAnswerCloseBtn: {
        width: normalize(40),
        height: normalize(40),
        borderRadius: normalize(20),
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F1F5F9',
    },
    questionAnswerScrollContent: {
        padding: normalize(18),
    },
    questionAnswerCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: normalize(22),
        borderWidth: 1,
        borderColor: '#D0D5DD',
        padding: normalize(20),
    },
    questionAnswerBody: {
        fontSize: normalize(14),
        color: '#334155',
        lineHeight: normalize(22),
        marginBottom: verticalScale(14),
    },
    questionAnswerExplanation: {
        fontSize: normalize(14),
        color: '#334155',
        lineHeight: normalize(22),
    },
    paymentWebViewContainer: {
        flex: 1,
        backgroundColor: '#F8FAFC',
    },
    paymentWebViewSafeArea: {
        backgroundColor: '#FFFFFF',
    },
    paymentWebViewHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        paddingHorizontal: normalize(20),
        paddingVertical: verticalScale(16),
        borderBottomWidth: 1,
        borderBottomColor: '#E2E8F0',
        backgroundColor: '#FFFFFF',
    },
    paymentWebViewHeaderText: {
        flex: 1,
        paddingRight: normalize(12),
    },
    paymentWebViewLabel: {
        alignSelf: 'flex-start',
        borderRadius: normalize(999),
        borderWidth: 1,
        borderColor: '#BFDBFE',
        backgroundColor: '#EFF6FF',
        color: '#1D4ED8',
        fontSize: normalize(10),
        fontWeight: '800',
        letterSpacing: 1,
        paddingHorizontal: normalize(12),
        paddingVertical: verticalScale(5),
        marginBottom: verticalScale(10),
    },
    paymentWebViewTitle: {
        fontSize: normalize(22),
        fontWeight: '900',
        color: '#0F172A',
        marginBottom: verticalScale(4),
    },
    paymentWebViewSubtitle: {
        fontSize: normalize(12),
        color: '#64748B',
        lineHeight: normalize(18),
    },
    paymentWebViewCloseBtn: {
        width: normalize(40),
        height: normalize(40),
        borderRadius: normalize(20),
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F1F5F9',
    },
    paymentWebViewBody: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    paymentWebViewLoading: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: normalize(20),
        backgroundColor: '#FFFFFF',
    },

    videoBankContainer: {
        flex: 1,
        backgroundColor: '#F8FAFC',
    },
    videoBankSafeArea: {
        backgroundColor: '#FFFFFF',
    },
    videoBankHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        paddingHorizontal: normalize(20),
        paddingVertical: verticalScale(16),
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
        gap: normalize(14),
    },
    videoBankHeaderText: {
        flex: 1,
    },
    videoBankLabel: {
        alignSelf: 'flex-start',
        borderRadius: normalize(999),
        borderWidth: 1,
        borderColor: '#BFDBFE',
        backgroundColor: '#EFF6FF',
        color: '#1D4ED8',
        fontSize: normalize(10),
        fontWeight: '800',
        letterSpacing: 1,
        paddingHorizontal: normalize(12),
        paddingVertical: verticalScale(5),
        marginBottom: verticalScale(10),
    },
    videoBankTitle: {
        fontSize: normalize(22),
        fontWeight: '800',
        color: '#101828',
        marginBottom: verticalScale(4),
    },
    videoBankSubtitle: {
        fontSize: normalize(12),
        color: '#667085',
        fontWeight: '600',
        textTransform: 'uppercase',
    },
    videoBankCloseBtn: {
        width: normalize(40),
        height: normalize(40),
        borderRadius: normalize(20),
        backgroundColor: '#F1F5F9',
        justifyContent: 'center',
        alignItems: 'center',
    },
    videoBankLoadingState: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        gap: normalize(10),
    },

    videoBankEmptyState: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        padding: normalize(20),
    },
    videoBankEmptyText: {
        marginTop: verticalScale(10),
        fontSize: normalize(13),
        color: '#667085',
        fontWeight: '600',
        textAlign: 'center',
    },
    videoBankListContent: {
        padding: normalize(18),
    },
    videoBankCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: normalize(18),
        borderWidth: 1,
        borderColor: '#E5E7EB',
        padding: normalize(16),
        minHeight: verticalScale(120),
        justifyContent: 'space-between',
    },
    videoBankCardTopRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: normalize(12),
    },
    videoBankPlayIconWrap: {
        width: normalize(36),
        height: normalize(36),
        borderRadius: normalize(18),
        backgroundColor: '#FEF2F2',
        justifyContent: 'center',
        alignItems: 'center',
    },
    videoBankCardTextWrap: {
        flex: 1,
    },
    videoBankCardTitle: {
        fontSize: normalize(16),
        fontWeight: '800',
        color: '#101828',
        marginBottom: verticalScale(4),
    },
    videoBankCardSubtitle: {
        fontSize: normalize(12),
        color: '#667085',
        lineHeight: normalize(18),
    },
    videoBankCardFooter: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: normalize(8),
        marginTop: verticalScale(12),
    },
    videoBankCardFooterText: {
        fontSize: normalize(12),
        fontWeight: '800',
        color: '#FF0000',
    },
});
