export const ROUTES = {
  SPLASH: 'Splash',
  ONBOARDING: 'Onboarding',
  LOGIN: 'Login',
  REGISTER: 'Register',
  FORGOT_PASSWORD: 'ForgotPassword',
  OTP_VERIFICATION: 'OtpVerification',
  CHANGE_PASSWORD: 'ChangePassword',
  EDIT_PROFILE: 'EditProfile',
  HOME: 'Home',
  RAPID_REVISION: 'RapidRevision',
  QUESTION_BANK: 'QuestionBank',
  MOCK_TESTS: 'MockTests',
  MOCK_TEST_SCREEN: 'MockTestScreen',
  SUBJECT_TESTS: 'SubjectTests',
  PYQ: 'PYQ',
  PREVIOUS_YEAR_QUESTIONS: 'PreviousYearQuestions',
  RESULTS: 'Results',
  PROFILE: 'Profile',
  NOTIFICATIONS: 'Notifications',
  SETTINGS: 'Settings',
  AUTH_STACK: 'AuthStack',
  MAIN_STACK: 'MainStack',
  BOTTOM_TABS: 'BottomTabs',
};
